// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mwmsrrammjgumscexuxh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im13bXNycmFtbWpndW1zY2V4dXhoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc2OTgzODAsImV4cCI6MjA2MzI3NDM4MH0.uJeMfHCC5HaNG0JosjNcxq76XDJECPdsvHOFCWKpP_E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);